services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs

  whoami:
    image: traefik/whoami
    expose:
      - "443"
    command:
      - --port=443
      - --cert=/certs/localhost.crt
      - --key=/certs/localhost.key
      - --verbose
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=443
      - VIRTUAL_PROTO=https
    volumes:
      - ./certs:/certs