services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs

  whoami:
    image: traefik/whoami
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=80
      - VIRTUAL_PROTO=https